GET http://localhost:8080/users
Authorization: Basic admin@miu.edu root

###

GET http://localhost:8080/books
Authorization: Basic admin@miu.edu root


###
GET http://localhost:8080/books
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbW1hbnVlbEBtaXUuZWR1IiwiaXNzIjoiQ1M1NDUgQVNTSUdOIEpXVCIsImlhdCI6MTY5NzQzNDE2NSwiZXhwIjoxNjk3NDM3NzY1fQ.-_cbxkjrDR9uRf-vlzI6wzqo-BMnDIyvD97zevY5sVWWSodY-Xo_19X5CcwauSZftLQXybZxV-4_WHXKMXH_qA

###

POST http://localhost:8080/books
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbW1hbnVlbEBtaXUuZWR1IiwiaXNzIjoiQ1M1NDUgQVNTSUdOIEpXVCIsImlhdCI6MTY5NzQzNDE2NSwiZXhwIjoxNjk3NDM3NzY1fQ.-_cbxkjrDR9uRf-vlzI6wzqo-BMnDIyvD97zevY5sVWWSodY-Xo_19X5CcwauSZftLQXybZxV-4_WHXKMXH_qA
Content-Type: application/json

{
  "title": "Algorithms and Data Structures",
  "isbn": "90128200201",
  "author": "Paul Smith",
  "publishedDate": "2009-06-11"

}

###

POST http://localhost:8080/books
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBtaXUuZWR1IiwiaXNzIjoiQ1M1NDUgQVNTSUdOIEpXVCIsImlhdCI6MTY5NzQzNDM5NCwiZXhwIjoxNjk3NDM3OTk0fQ.nOhZrQaHoX81x2VZJPHhyQ1qyQIP5L4wPO0yA3iuJDnAEVVRsnLn5Zwo2Jk7CUqawNaszewQA0Y6IbcFSCIG2A
Content-Type: application/json

{
  "title": "Algorithms and Data Structures",
  "isbn": "90128200201",
  "author": "Paul Smith",
  "publishedDate": "2009-06-11"

}

###

GET http://localhost:8080/books/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBtaXUuZWR1IiwiaXNzIjoiQ1M1NDUgQVNTSUdOIEpXVCIsImlhdCI6MTY5NzQzNDM5NCwiZXhwIjoxNjk3NDM3OTk0fQ.nOhZrQaHoX81x2VZJPHhyQ1qyQIP5L4wPO0yA3iuJDnAEVVRsnLn5Zwo2Jk7CUqawNaszewQA0Y6IbcFSCIG2A

###

POST http://localhost:8080/books
Authorization: Basic admin@miu.edu root
Content-Type: application/json

{
  "title": "Test-Driven Development by example",
  "isbn": "96162038546",
  "author": "Michael Kent",
  "publishedDate": "2022-03-14"

}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "email":"emmanuel@miu.edu",
  "password":"123456"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email":"admin@miu.edu",
  "password":"root"
}